#!/bin/bash
set -e
if systemctl list-unit-files | grep -q '^zwavemqtt\.service'; then
    systemctl stop zwavemqtt || true
    systemctl disable zwavemqtt || true
    rm -f /etc/systemd/system/zwavemqtt.service
    systemctl daemon-reload || true
fi
rm -rf /opt/zwave-js-ui
exit 0
